server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: rally-master-api
    
  profiles:
    active: dev
    
  datasource:
    url: jdbc:postgresql://localhost:5432/rally_master
    username: rally_user
    password: rally_password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/api/v1
          
logging:
  level:
    com.rallymaster: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

rally-master:
  jwt:
    secret: ${JWT_SECRET:rally-master-default-secret-key-change-in-production}
    expiration: 86400000 # 24 hours
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:8081
    allowed-methods: 
      - GET
      - POST 
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/rally_master_dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:15:///rally_master_test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
      
---
spring:
  config:
    activate:
      on-profile: test-h2
  datasource:
    url: jdbc:h2:mem:rally_master_test
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
    
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rally_master}
    username: ${DATABASE_USERNAME:rally_user}
    password: ${DATABASE_PASSWORD:rally_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: false
    
logging:
  level:
    com.rallymaster: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN